// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv2zdzDZCOeK3bZ7ecnib7Ad2e3lDtcfk',
    appId: '1:841128043312:web:21d6559e400f822b531ef5',
    messagingSenderId: '841128043312',
    projectId: 'firebase-project-basic',
    authDomain: 'fir-project-basic-806d7.firebaseapp.com',
    storageBucket: 'firebase-project-basic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGUmouD9Ef2R4A9kVwnxLtsX7JCElltY',
    appId: '1:841128043312:android:603130723a5b40f2531ef5',
    messagingSenderId: '841128043312',
    projectId: 'firebase-project-basic',
    storageBucket: 'firebase-project-basic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn-TV9oOF82Zzl2aIDWvUB2a5VhzCMUIA',
    appId: '1:841128043312:ios:6bc5527dc750036b531ef5',
    messagingSenderId: '841128043312',
    projectId: 'firebase-project-basic',
    storageBucket: 'firebase-project-basic.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn-TV9oOF82Zzl2aIDWvUB2a5VhzCMUIA',
    appId: '1:841128043312:ios:6bc5527dc750036b531ef5',
    messagingSenderId: '841128043312',
    projectId: 'firebase-project-basic',
    storageBucket: 'firebase-project-basic.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv2zdzDZCOeK3bZ7ecnib7Ad2e3lDtcfk',
    appId: '1:841128043312:web:0a67885f4057dc82531ef5',
    messagingSenderId: '841128043312',
    projectId: 'firebase-project-basic',
    authDomain: 'fir-project-basic-806d7.firebaseapp.com',
    storageBucket: 'firebase-project-basic.appspot.com',
  );
}
